name: Nightly build
on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
  
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8

    - name: Increment Version
      env:
        VERSION_s: 4+GITHUB_RUN_NUMBER
        VERSION_f: "2.2.0-dev$VERSION_s"
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.4.2
    
    - name: Execute Gradle build
      run: ./gradlew build
      
    - uses: "dciborow/action-github-releases@v1.0.1"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "$VERSION_f"
        prerelease: true
        title: "Version 2.2.0, Pre-release $VERSION_s (Nightly)"
        generate_release_notes: true
        files: |
          LICENSE
          ChangeLog.md
          build/libs/**.jar
        
